In [2]:
import pandas as pd

In [3]:
adidas = pd.read_csv('adidas.csv')

In [4]:
adidas.shape

(845, 20)

In [5]:
adidas.columns

Index(['url', 'name', 'sku', 'selling_price', 'original_price', 'currency',
       'availability', 'color', 'category', 'source', 'source_website',
       'breadcrumbs', 'description', 'brand', 'images', 'country', 'language',
       'average_rating', 'reviews_count', 'crawled_at'],
      dtype='object')

In [ ]:
#Ejercicio 1

In [6]:
cols_validas = []
cols_many_levels = []
cols_one_level = []

size_df = adidas.shape[0]
umbral = .98

for c_ in adidas.columns:
    
    niveles = adidas.loc[ : , [c_] ].drop_duplicates().shape[0]
    
    if ( niveles / size_df ) >= umbral:
        cols_many_levels.append(c_)
    elif niveles == 1:
        cols_one_level.append(c_)
    else:
       cols_validas.append(c_)

In [7]:
#Columnas que si cumplen
cols_many_levels

['url', 'sku', 'images', 'crawled_at']

In [8]:
adidas.loc[ :  , cols_many_levels ].drop_duplicates()

,url,sku,images,crawled_at
0,https://www.adidas.com/us/beach-shorts/FJ5089....,FJ5089,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:50:17.331255
1,https://www.adidas.com/us/five-ten-kestrel-lac...,BC0770,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:50:17.423830
2,https://www.adidas.com/us/mexico-away-jersey/G...,GC7946,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:50:17.530834
3,https://www.adidas.com/us/five-ten-hiangle-pro...,FV4744,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:50:17.615054
4,https://www.adidas.com/us/mesh-broken-stripe-p...,GM0239,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:50:17.702680
...,...,...,...,...
840,https://www.adidas.com/us/supernova-plus-shoes...,FX2858,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:52:31.937924
841,https://www.adidas.com/us/choigo-shoes/H00667....,H00667,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:52:32.014973
842,https://www.adidas.com/us/daily-3.0-shoes/GZ77...,GZ7705,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:52:32.208426
843,https://www.adidas.com/us/daily-3.0-shoes/GZ77...,GZ7706,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:52:32.293622
844,https://www.adidas.com/us/choigo-shoes/FY6503....,FY6503,"https://assets.adidas.com/images/w_600,f_auto,...",2021-10-23 17:52:32.398104

In [9]:
cols_validas

['name',
 'selling_price',
 'original_price',
 'availability',
 'color',
 'category',
 'breadcrumbs',
 'description',
 'average_rating',
 'reviews_count']

In [ ]:
#Ejercicio 2

In [10]:
cols_validas2 = []
cols_many_levels2 = []
cols_more_level = []

size_df = adidas.shape[0]
umbral = .98

for c_ in adidas.columns:
    
    niveles = adidas.loc[ : , [c_] ].drop_duplicates().shape[0]
    
    if ( niveles / size_df ) >= umbral:
        cols_many_levels2.append(c_)
    elif niveles >= 3 & niveles <= 6:
        cols_more_level.append(c_)
    else:
       cols_validas2.append(c_)

In [11]:
cols_more_level

['name',
 'selling_price',
 'original_price',
 'currency',
 'availability',
 'color',
 'category',
 'source',
 'source_website',
 'breadcrumbs',
 'description',
 'brand',
 'country',
 'language',
 'average_rating',
 'reviews_count']

In [14]:
adidas.loc[ :  , cols_more_level ]

,name,selling_price,original_price,currency,availability,color,category,source,source_website,breadcrumbs,description,brand,country,language,average_rating,reviews_count
0,Beach Shorts,40,NaN,USD,InStock,Black,Clothing,adidas United States,https://www.adidas.com,Women/Clothing,Splashing in the surf. Making memories with yo...,adidas,USA,en,4.5,35
1,Five Ten Kestrel Lace Mountain Bike Shoes,150,NaN,USD,InStock,Grey,Shoes,adidas United States,https://www.adidas.com,Women/Shoes,Lace up and get after it. The Five Ten Kestrel...,adidas,USA,en,4.8,4
2,Mexico Away Jersey,70,NaN,USD,InStock,White,Clothing,adidas United States,https://www.adidas.com,Kids/Clothing,"Clean and crisp, this adidas Mexico Away Jerse...",adidas,USA,en,4.9,42
3,Five Ten Hiangle Pro Competition Climbing Shoes,160,NaN,USD,InStock,Black,Shoes,adidas United States,https://www.adidas.com,Five Ten/Shoes,The Hiangle Pro takes on the classic shape of ...,adidas,USA,en,3.7,7
4,Mesh Broken-Stripe Polo Shirt,65,NaN,USD,InStock,Blue,Clothing,adidas United States,https://www.adidas.com,Men/Clothing,Step up to the tee relaxed. This adidas golf p...,adidas,USA,en,4.7,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
840,Supernova+ Shoes,72,$120,USD,InStock,White,Shoes,adidas United States,https://www.adidas.com,Women/Shoes,Take off. Touch down. Repeat. These adidas run...,adidas,USA,en,4.3,151
841,Choigo Shoes,70,$100,USD,InStock,White,Shoes,adidas United States,https://www.adidas.com,Women/Shoes,"If you want drama, the bold female track and f...",adidas,USA,en,4.7,135
842,Daily 3.0 Shoes,35,$50,USD,InStock,Black,Shoes,adidas United States,https://www.adidas.com,Kids/Shoes,The style is in the details of the Daily 3.0 S...,adidas,USA,en,4.7,190
843,Daily 3.0 Shoes,40,$50,USD,InStock,Pink,Shoes,adidas United States,https://www.adidas.com,Kids/Shoes,The style is in the details of the Daily 3.0 S...,adidas,USA,en,4.7,190
844,Choigo Shoes,70,$100,USD,InStock,Black,Shoes,adidas United States,https://www.adidas.com,Women/Shoes,Take your style to bold new heights. Throw in ...,adidas,USA,en,4.7,135

In [18]:
adidas.loc[ :  , "color"].value_counts() / size_df

White         0.262722
Black         0.221302
Blue          0.123077
Grey          0.095858
Pink          0.073373
Green         0.069822
Purple        0.036686
Red           0.029586
Multicolor    0.023669
Yellow        0.020118
Orange        0.013018
Burgundy      0.010651
Beige         0.007101
Multi         0.004734
Gold          0.003550
Turquoise     0.002367
Silver        0.001183
Brown         0.001183
Name: color, dtype: float64